import os

BASE_APP_TITLE = "dekapu-osc-clicker"
APP_VERSION = os.getenv("DEKAPU_OSC_CLICKER_VERSION", "").strip()
APP_TITLE = f"{BASE_APP_TITLE} {APP_VERSION}" if APP_VERSION else BASE_APP_TITLE
WINDOW_SIZE = "540x280"

VRCHAT_OSC_IP = "127.0.0.1"
VRCHAT_OSC_PORT = 9000
DEFAULT_CLICK_DELAY = 0.2
DEFAULT_CLICK_PRESS_DURATION = 0.08
LOG_FILE_PATTERN = "output_log_*.txt"
LOG_URL_MARKER = "[DSM SaveURL] Generated URL:"
MONITOR_POLL_INTERVAL = 0.5
